# docker run --name honor-api -e  -p 5432:5432 

version: '3'

services:
  pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USER=pablo
      - POSTGRESQL_PASSWORD=!2107ph
      - POSTGRESQL_DATABASE=apisolid